// ggml-metal-embed.c
// Generated wrapper for embedded Metal library
// This file defines the symbols expected by ggml-metal-device.m when GGML_METAL_EMBED_LIBRARY is defined

// The xxd output uses a default array name based on file path. We need to create proper start/end symbols.
// Using the stdin__ array generated by xxd from stdin

const char ggml_metallib_start[] = {
#include "ggml-metal-embed.h"
};

const char* const ggml_metallib_end = ggml_metallib_start + sizeof(ggml_metallib_start);
